select = ["ALL"]
# Disable trailing commas, line length (black does it)
ignore = [
    "COM",
    "E501",
    "D",
    "S101",
    "ERA",
    "ANN101",
    "G004",
    "PLR2004",
    "D211",
    "D213",
    "TRY",
    "EM",
]

# No removing of #noqa, erasing commented code
unfixable = ["RUF100", "ERA"]

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"path/to/file.py" = ["E402"]

[isort]
known-first-party = ["adpbench", "tests"]
force-single-line = true
force-sort-within-sections = true
single-line-exclusions = ["typing"]
order-by-type = false
